/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as VendedorIndexRouteImport } from './routes/vendedor.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VendedorNovoRouteImport } from './routes/vendedor.novo'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSupabaseRouteImport } from './routes/_authenticated/supabase'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedNfeRouteImport } from './routes/_authenticated/nfe'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as ApiTenantSplatRouteImport } from './routes/api/tenant/$'
import { Route as ApiPublicV1RouteImport } from './routes/api/public/v1'
import { Route as ApiPublicNfeioWebhookRouteImport } from './routes/api/public/nfeio-webhook'
import { Route as AuthenticatedRelatoriosCatalogoRouteImport } from './routes/_authenticated/relatorios.catalogo'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos.novo'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos.$id'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated/pedidos.novo'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque.movimentacoes'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as ApiPublicV1ProdutosRouteImport } from './routes/api/public/v1/produtos'
import { Route as ApiPublicV1PedidosRouteImport } from './routes/api/public/v1/pedidos'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorIndexRoute = VendedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VendedorNovoRoute = VendedorNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => VendedorRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupabaseRoute = AuthenticatedSupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNfeRoute = AuthenticatedNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const ApiTenantSplatRoute = ApiTenantSplatRouteImport.update({
  id: '/api/tenant/$',
  path: '/api/tenant/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Route = ApiPublicV1RouteImport.update({
  id: '/api/public/v1',
  path: '/api/public/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNfeioWebhookRoute = ApiPublicNfeioWebhookRouteImport.update({
  id: '/api/public/nfeio-webhook',
  path: '/api/public/nfeio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosCatalogoRoute =
  AuthenticatedRelatoriosCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProdutosRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProdutosRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/pedidos/novo',
    path: '/pedidos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const ApiPublicV1ProdutosRoute = ApiPublicV1ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => ApiPublicV1Route,
} as any)
const ApiPublicV1PedidosRoute = ApiPublicV1PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ApiPublicV1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/supabase': typeof AuthenticatedSupabaseRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedor/novo': typeof VendedorNovoRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/relatorios/catalogo': typeof AuthenticatedRelatoriosCatalogoRoute
  '/api/public/nfeio-webhook': typeof ApiPublicNfeioWebhookRoute
  '/api/public/v1': typeof ApiPublicV1RouteWithChildren
  '/api/tenant/$': typeof ApiTenantSplatRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/api/public/v1/pedidos': typeof ApiPublicV1PedidosRoute
  '/api/public/v1/produtos': typeof ApiPublicV1ProdutosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/supabase': typeof AuthenticatedSupabaseRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedor/novo': typeof VendedorNovoRoute
  '/': typeof AuthenticatedIndexRoute
  '/vendedor': typeof VendedorIndexRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/relatorios/catalogo': typeof AuthenticatedRelatoriosCatalogoRoute
  '/api/public/nfeio-webhook': typeof ApiPublicNfeioWebhookRoute
  '/api/public/v1': typeof ApiPublicV1RouteWithChildren
  '/api/tenant/$': typeof ApiTenantSplatRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/api/public/v1/pedidos': typeof ApiPublicV1PedidosRoute
  '/api/public/v1/produtos': typeof ApiPublicV1ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/nfe': typeof AuthenticatedNfeRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/_authenticated/supabase': typeof AuthenticatedSupabaseRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedor/novo': typeof VendedorNovoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/_authenticated/relatorios/catalogo': typeof AuthenticatedRelatoriosCatalogoRoute
  '/api/public/nfeio-webhook': typeof ApiPublicNfeioWebhookRoute
  '/api/public/v1': typeof ApiPublicV1RouteWithChildren
  '/api/tenant/$': typeof ApiTenantSplatRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/api/public/v1/pedidos': typeof ApiPublicV1PedidosRoute
  '/api/public/v1/produtos': typeof ApiPublicV1ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vendedor'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/nfe'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/supabase'
    | '/usuarios'
    | '/vendedor/novo'
    | '/vendedor/'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/estoque/movimentacoes'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/relatorios/catalogo'
    | '/api/public/nfeio-webhook'
    | '/api/public/v1'
    | '/api/tenant/$'
    | '/estoque/'
    | '/pedidos/'
    | '/api/public/v1/pedidos'
    | '/api/public/v1/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/fornecedores'
    | '/nfe'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/supabase'
    | '/usuarios'
    | '/vendedor/novo'
    | '/'
    | '/vendedor'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/estoque/movimentacoes'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/relatorios/catalogo'
    | '/api/public/nfeio-webhook'
    | '/api/public/v1'
    | '/api/tenant/$'
    | '/estoque'
    | '/pedidos'
    | '/api/public/v1/pedidos'
    | '/api/public/v1/produtos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/vendedor'
    | '/_authenticated/caixa'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/fornecedores'
    | '/_authenticated/nfe'
    | '/_authenticated/pdv'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/supabase'
    | '/_authenticated/usuarios'
    | '/vendedor/novo'
    | '/_authenticated/'
    | '/vendedor/'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedidos/novo'
    | '/_authenticated/produtos/$id'
    | '/_authenticated/produtos/novo'
    | '/_authenticated/relatorios/catalogo'
    | '/api/public/nfeio-webhook'
    | '/api/public/v1'
    | '/api/tenant/$'
    | '/_authenticated/estoque/'
    | '/_authenticated/pedidos/'
    | '/api/public/v1/pedidos'
    | '/api/public/v1/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VendedorRoute: typeof VendedorRouteWithChildren
  ApiPublicNfeioWebhookRoute: typeof ApiPublicNfeioWebhookRoute
  ApiPublicV1Route: typeof ApiPublicV1RouteWithChildren
  ApiTenantSplatRoute: typeof ApiTenantSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/': {
      id: '/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof VendedorIndexRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/vendedor/novo': {
      id: '/vendedor/novo'
      path: '/novo'
      fullPath: '/vendedor/novo'
      preLoaderRoute: typeof VendedorNovoRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supabase': {
      id: '/_authenticated/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof AuthenticatedSupabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nfe': {
      id: '/_authenticated/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AuthenticatedNfeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/api/tenant/$': {
      id: '/api/tenant/$'
      path: '/api/tenant/$'
      fullPath: '/api/tenant/$'
      preLoaderRoute: typeof ApiTenantSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1': {
      id: '/api/public/v1'
      path: '/api/public/v1'
      fullPath: '/api/public/v1'
      preLoaderRoute: typeof ApiPublicV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nfeio-webhook': {
      id: '/api/public/nfeio-webhook'
      path: '/api/public/nfeio-webhook'
      fullPath: '/api/public/nfeio-webhook'
      preLoaderRoute: typeof ApiPublicNfeioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios/catalogo': {
      id: '/_authenticated/relatorios/catalogo'
      path: '/catalogo'
      fullPath: '/relatorios/catalogo'
      preLoaderRoute: typeof AuthenticatedRelatoriosCatalogoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedProdutosRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedProdutosRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/api/public/v1/produtos': {
      id: '/api/public/v1/produtos'
      path: '/produtos'
      fullPath: '/api/public/v1/produtos'
      preLoaderRoute: typeof ApiPublicV1ProdutosRouteImport
      parentRoute: typeof ApiPublicV1Route
    }
    '/api/public/v1/pedidos': {
      id: '/api/public/v1/pedidos'
      path: '/pedidos'
      fullPath: '/api/public/v1/pedidos'
      preLoaderRoute: typeof ApiPublicV1PedidosRouteImport
      parentRoute: typeof ApiPublicV1Route
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedProdutosRouteChildren {
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
}

const AuthenticatedProdutosRouteChildren: AuthenticatedProdutosRouteChildren = {
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
}

const AuthenticatedProdutosRouteWithChildren =
  AuthenticatedProdutosRoute._addFileChildren(
    AuthenticatedProdutosRouteChildren,
  )

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosCatalogoRoute: typeof AuthenticatedRelatoriosCatalogoRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosCatalogoRoute: AuthenticatedRelatoriosCatalogoRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedNfeRoute: typeof AuthenticatedNfeRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedSupabaseRoute: typeof AuthenticatedSupabaseRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedNfeRoute: AuthenticatedNfeRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedSupabaseRoute: AuthenticatedSupabaseRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VendedorRouteChildren {
  VendedorNovoRoute: typeof VendedorNovoRoute
  VendedorIndexRoute: typeof VendedorIndexRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorNovoRoute: VendedorNovoRoute,
  VendedorIndexRoute: VendedorIndexRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

interface ApiPublicV1RouteChildren {
  ApiPublicV1PedidosRoute: typeof ApiPublicV1PedidosRoute
  ApiPublicV1ProdutosRoute: typeof ApiPublicV1ProdutosRoute
}

const ApiPublicV1RouteChildren: ApiPublicV1RouteChildren = {
  ApiPublicV1PedidosRoute: ApiPublicV1PedidosRoute,
  ApiPublicV1ProdutosRoute: ApiPublicV1ProdutosRoute,
}

const ApiPublicV1RouteWithChildren = ApiPublicV1Route._addFileChildren(
  ApiPublicV1RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VendedorRoute: VendedorRouteWithChildren,
  ApiPublicNfeioWebhookRoute: ApiPublicNfeioWebhookRoute,
  ApiPublicV1Route: ApiPublicV1RouteWithChildren,
  ApiTenantSplatRoute: ApiTenantSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
