/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated/pedidos.novo'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedPedidosRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pdv'
    | '/pedidos'
    | '/pedidos/$id'
    | '/pedidos/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/pdv' | '/pedidos' | '/' | '/pedidos/$id' | '/pedidos/novo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/pdv'
    | '/_authenticated/pedidos'
    | '/_authenticated/'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedidos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
  }
}

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
