/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedNfeRouteImport } from './routes/_authenticated/nfe'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFidelidadeRouteImport } from './routes/_authenticated/fidelidade'
import { Route as AuthenticatedFiadoRouteImport } from './routes/_authenticated/fiado'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComandasRouteImport } from './routes/_authenticated/comandas'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos.novo'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos.$id'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated/pedidos.novo'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque.movimentacoes'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNfeRoute = AuthenticatedNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFidelidadeRoute = AuthenticatedFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiadoRoute = AuthenticatedFiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComandasRoute = AuthenticatedComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProdutosRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProdutosRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedPedidosRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPedidosRoute,
} as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/comandas': typeof AuthenticatedComandasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/fiado': typeof AuthenticatedFiadoRoute
  '/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/comandas': typeof AuthenticatedComandasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/fiado': typeof AuthenticatedFiadoRoute
  '/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/comandas': typeof AuthenticatedComandasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/fiado': typeof AuthenticatedFiadoRoute
  '/_authenticated/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/nfe': typeof AuthenticatedNfeRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backup'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/comandas'
    | '/configuracoes'
    | '/contas'
    | '/delivery'
    | '/despesas'
    | '/estoque'
    | '/fiado'
    | '/fidelidade'
    | '/financeiro'
    | '/integracoes'
    | '/logs'
    | '/movimentacoes'
    | '/nfe'
    | '/pdv'
    | '/pedidos'
    | '/permissoes'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/clientes/$id'
    | '/estoque/movimentacoes'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/produtos/$id'
    | '/produtos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backup'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/comandas'
    | '/configuracoes'
    | '/contas'
    | '/delivery'
    | '/despesas'
    | '/estoque'
    | '/fiado'
    | '/fidelidade'
    | '/financeiro'
    | '/integracoes'
    | '/logs'
    | '/movimentacoes'
    | '/nfe'
    | '/pdv'
    | '/pedidos'
    | '/permissoes'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/'
    | '/clientes/$id'
    | '/estoque/movimentacoes'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/produtos/$id'
    | '/produtos/novo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backup'
    | '/_authenticated/caixa'
    | '/_authenticated/categorias'
    | '/_authenticated/clientes'
    | '/_authenticated/comandas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas'
    | '/_authenticated/delivery'
    | '/_authenticated/despesas'
    | '/_authenticated/estoque'
    | '/_authenticated/fiado'
    | '/_authenticated/fidelidade'
    | '/_authenticated/financeiro'
    | '/_authenticated/integracoes'
    | '/_authenticated/logs'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/nfe'
    | '/_authenticated/pdv'
    | '/_authenticated/pedidos'
    | '/_authenticated/permissoes'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedidos/novo'
    | '/_authenticated/produtos/$id'
    | '/_authenticated/produtos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nfe': {
      id: '/_authenticated/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AuthenticatedNfeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fidelidade': {
      id: '/_authenticated/fidelidade'
      path: '/fidelidade'
      fullPath: '/fidelidade'
      preLoaderRoute: typeof AuthenticatedFidelidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiado': {
      id: '/_authenticated/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof AuthenticatedFiadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comandas': {
      id: '/_authenticated/comandas'
      path: '/comandas'
      fullPath: '/comandas'
      preLoaderRoute: typeof AuthenticatedComandasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedProdutosRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedProdutosRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedProdutosRouteChildren {
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
}

const AuthenticatedProdutosRouteChildren: AuthenticatedProdutosRouteChildren = {
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
}

const AuthenticatedProdutosRouteWithChildren =
  AuthenticatedProdutosRoute._addFileChildren(
    AuthenticatedProdutosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedComandasRoute: typeof AuthenticatedComandasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedFiadoRoute: typeof AuthenticatedFiadoRoute
  AuthenticatedFidelidadeRoute: typeof AuthenticatedFidelidadeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedNfeRoute: typeof AuthenticatedNfeRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedComandasRoute: AuthenticatedComandasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedFiadoRoute: AuthenticatedFiadoRoute,
  AuthenticatedFidelidadeRoute: AuthenticatedFidelidadeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedNfeRoute: AuthenticatedNfeRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
